baseURL = "https://marcellogalhardo.dev/"
languageCode = "en-us"
title = "Marcello Galhardo"
theme = "anubis"
paginate = 10
googleAnalytics = "UA-123-45"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2