baseURL = "https://marcellogalhardo.dev/"
languageCode = "en-us"
theme = "hello-friend-ng" # "anubis"
paginate = 10
googleAnalytics = "UA-123-45"
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Marcello Galhardo"
    subtitle = "Senior Software Engineer @ N26"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "marcellogalhardo.dev"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3
