baseURL = "https://marcellogalhardo.dev/"
languageCode = "en-us"
theme = "paper-mod" # "paper" # "hello-friend-ng" # "anubis"
paginate = 10
googleAnalytics = "G-7LK7ENB813"
enableRobotsTXT = true

[params]
  # Just a custom image variable, please define it in .md files for content.
  image = "/logo.png"

[languages]
  [languages.en]
    title = "Marcello Galhardo"
    subtitle = "Android Software Engineer"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "marcellogalhardo.dev"
      logoHomeLink = "/logo.png"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3

  [[menu.main]]
    identifier = "uses"
    name = "Uses"
    url = "/uses"
    weight = 4
