author = "Marcello Galhardo"
email = "marcello.galhardo@gmail.com" # used for microformats
avatar = "https://avatars3.githubusercontent.com/u/4348197?s=460&v=4" # used for microformats
description = "Marcello's Personal Blog"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto" # https://themes.gohugo.io/hugo-theme-anubis/#dark-mode
readMore = false
