defaultTheme: dark
disableThemeToggle: true
image: /logo.png

profileMode:
  enabled: true
  title: "Marcello Galhardo"
  subtitle: "Android Software Engineer"
  imageUrl: "https://avatars.githubusercontent.com/u/4348197?s=400&u=c27e3f938a61471e2eebc00d6c8ab8826b0af816&v=4"
  imageTitle: "Profile Picture"
  imageWidth: 120
  imageHeight: 120
  buttons:
    - name: Posts
      url: "/posts"

cover:
  image: "https://avatars.githubusercontent.com/u/4348197?s=400&u=c27e3f938a61471e2eebc00d6c8ab8826b0af816&v=4"

socialIcons:
  - name: "twitter"
    url: "https://twitter.com/marcellogalhard"
  - name: "github"
    url: "https://github.com/marcellogalhardo/"
  - name: "linkedin"
    url: "https://www.linkedin.com/in/marcellogalhardo/"
